sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lucaspenido/docker-react-udemy -f Dockerfile.dev .

script:
  - docker run -e CI=true lucaspenido/docker-react-udemy npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react-udemy"
  env: "DockerReactUdemy-env"
  bucket_name: "elasticbeanstalk-sa-east-1-486748495912"
  bucket_path: "docker-react-udemy"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
