sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lucaspenido/docker-react-udemy -f Dockerfile.dev .

script:
  - docker run lucaspenido/docker-react-udemy npm run test -- --coverage
